### ISSUE TITLE
Minifying error

### ISSUE THREAD

**Issue by ruikle** [abagshaw/brackets-minifier#30]
When minifying
 `@font-face {
  src: url("../fonts/icons.eot?45335921");
  src: url("../fonts/icons.eot?45335921#iefix") format("embedded-opentype"), url("../fonts/icons.woff2?45335921") format("woff2"), url("../fonts/icons.woff?45335921") format("woff"), url("../fonts/icons.ttf?45335921") format("truetype"), url("../fonts/icons.svg?45335921#fontello") format("svg");
  font-family: 'ftwp-icon'; }`, 

the result is
 `@font-face{src:url(fonts/icons.eot?45335921);src:url(fonts/icons.eot?45335921#iefix) format("embedded-opentype"),url(fonts/icons.woff2?45335921) format("woff2"),url(fonts/icons.woff?45335921) format("woff"),url(fonts/icons.ttf?45335921) format("truetype"),url(fonts/icons.svg?45335921#fontello) format("svg");font-family:ftwp-icon}`.

It deleted the "../" character. Could you fix this bug? Thanks.

**Comment by abagshaw** [comment]
CSS minification in brackets-minifier is handled by [clean-css](https://github.com/jakubpawlowicz/clean-css). Please direct your issue to their repo as they will be better able to address it. 

There may be an option that can be set to correct the behaviour you are mentioning. If the issue is indeed a bug feel free to let me know when [clean-css](https://github.com/jakubpawlowicz/clean-css) patches it and I'll update the dependency here.
